/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.raven.form;

import com.nhomsau.domainmodel.Lop;
import com.nhomsau.domainmodel.SinhVien;
import com.nhomsau.repository.impl.LopRepository;
import com.nhomsau.service.impl.SinhVienService;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class Form_DanhSachSinhVien extends javax.swing.JPanel {

    /**
     * Creates new form ok
     */
    LopRepository lopRepository;
    SinhVienService sinhVienService;
    DefaultTableModel model;
    DefaultComboBoxModel<String> cbBoxModel;

    public Form_DanhSachSinhVien() {
        initComponents();
        tblSinhVien.fixTable(jScrollPane1);
        model = (DefaultTableModel) tblSinhVien.getModel();
        cbBoxModel = (DefaultComboBoxModel<String>) cbxLop.getModel();
        lopRepository = new LopRepository();
        sinhVienService = new SinhVienService();
        cbxLop.setLabeText("Lớp");
        txtTimKiem.setLabelText("Tìm kiếm theo maSV");
        fillAllLop();
        loadTable(getSinhViens());
    }

    private void fillAllLop() {
        List<Lop> lops = lopRepository.getAllLop();
        for (Lop lop : lops) {
            cbBoxModel.addElement(lop.getTenLop());
        }
        cbxLop.setModel(cbBoxModel);
    }

    private List<SinhVien> getSinhViens() {
        List<SinhVien> listSinhViens = new ArrayList<>();
        String tenLop = (String) cbxLop.getSelectedItem();
        Lop lop = lopRepository.getLop(tenLop);
        String idLop = lop.getId();
        listSinhViens = sinhVienService.getSinhViens(idLop);
        return listSinhViens;
    }

    private void loadTable(List<SinhVien> list) {
        model.setRowCount(0);
        int i = 1;
        for (SinhVien sv : list) {
            model.addRow(new Object[]{i, sv.getMa(), sv.getHoTen(), sv.getNgaySinh(), sv.getDiaChi(), sv.getEmail(), sv.getSdt()});
            i++;
        }
    }

//    private List<SinhVien> fillAllSinhVien(){
//        String tenLop = cbxLop.getLabeText();
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTransparent1 = new com.raven.swing.PanelTransparent();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSinhVien = new com.raven.swing.table.Table();
        cbxLop = new com.raven.swing.combobox.Combobox();
        txtTimKiem = new com.raven.swing.textfield.TextField();

        panelTransparent1.setOpaque(true);

        tblSinhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "MÃ ", "Họ tên", "Ngày sinh", "Địa chỉ", "Email", "SĐT"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSinhVien);

        javax.swing.GroupLayout panelTransparent1Layout = new javax.swing.GroupLayout(panelTransparent1);
        panelTransparent1.setLayout(panelTransparent1Layout);
        panelTransparent1Layout.setHorizontalGroup(
            panelTransparent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 996, Short.MAX_VALUE)
        );
        panelTransparent1Layout.setVerticalGroup(
            panelTransparent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparent1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cbxLop.setToolTipText("Lớp");
        cbxLop.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxLopItemStateChanged(evt);
            }
        });

        txtTimKiem.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtTimKiemPropertyChange(evt);
            }
        });
        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTransparent1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbxLop, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(panelTransparent1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbxLopItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxLopItemStateChanged
        // TODO add your handling code here:
        List<SinhVien> listSinhViens = new ArrayList<>();
        String tenLop = (String) cbxLop.getSelectedItem();
        Lop lop = lopRepository.getLop(tenLop);
        String idLop = lop.getId();
        listSinhViens = sinhVienService.getSinhViens(idLop);
        loadTable(listSinhViens);
    }//GEN-LAST:event_cbxLopItemStateChanged

    private void txtTimKiemPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtTimKiemPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemPropertyChange

    private void txtTimKiemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyPressed
//         TODO add your handling code here:
//        String timKiem = txtTimKiem.getText();
//        List<SinhVien> list = new ArrayList<>();
//        List<SinhVien> listSinhViens = new ArrayList<>();
//        String tenLop = (String) cbxLop.getSelectedItem();
//        Lop lop = lopRepository.getLop(tenLop);
//        String idLop = lop.getId();
//        listSinhViens = sinhVienService.getSinhViens(idLop);
//        for (SinhVien sv : listSinhViens) {
//            if (sv.getMa().contains(timKiem)) {
//                list.add(sv);
//            }
//        }
//            loadTable(list);
    }//GEN-LAST:event_txtTimKiemKeyPressed

    private void txtTimKiemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyTyped
        // TODO add your handling code here:
        String timKiem = txtTimKiem.getText();
        List<SinhVien> list = new ArrayList<>();
        List<SinhVien> listSinhViens = new ArrayList<>();
        String tenLop = (String) cbxLop.getSelectedItem();
        Lop lop = lopRepository.getLop(tenLop);
        String idLop = lop.getId();
        listSinhViens = sinhVienService.getSinhViens(idLop);
        for (SinhVien sv : listSinhViens) {
            if (sv.getMa().contains(timKiem)) {
                list.add(sv);
            }
        }
        loadTable(list);
    }//GEN-LAST:event_txtTimKiemKeyTyped

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.swing.combobox.Combobox cbxLop;
    private javax.swing.JScrollPane jScrollPane1;
    private com.raven.swing.PanelTransparent panelTransparent1;
    private com.raven.swing.table.Table tblSinhVien;
    private com.raven.swing.textfield.TextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
