/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.nhomsau.view;

import com.nhomsau.service.IManageMajorService;
import com.nhomsau.service.IManageManagerService;
import com.nhomsau.service.IManageSemesterService;
import com.nhomsau.service.IManageSubjectService;
import com.nhomsau.service.impl.ManageMajorService;
import com.nhomsau.service.impl.ManageManagerService;
import com.nhomsau.service.impl.ManageSemesterService;
import com.nhomsau.service.impl.ManageSubjectService;
import com.nhomsau.viewmodel.ManageMajor;
import com.nhomsau.viewmodel.ManageSemester;
import com.nhomsau.viewmodel.ManageSubject;
import com.nhomsau.viewmodel.Statistical;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import jdk.dynalink.beans.StaticClass;

/**
 *
 * @author Admin
 */
public class Form_Statistical extends javax.swing.JPanel {

    /**
     * Creates new form Form_Statistical
     */
    private IManageSubjectService subjectService;
    private IManageMajorService majorService;
    private IManageSemesterService semesterService;
    private IManageManagerService managerService;
    private DefaultTableModel tblModel;

    public Form_Statistical() {
//        initComponents();
//        managerService = new ManageManagerService();
//        subjectService = new ManageSubjectService();
//        majorService = new ManageMajorService();
//        semesterService = new ManageSemesterService();
//        loadCBB();
//        loadTable();
    }

    private void loadCBB() {
//        List<ManageSubject> listSubject = subjectService.findAll();
//        cbbSubjects.setModel(new DefaultComboBoxModel(listSubject.toArray()));
//        List<ManageMajor> listManageMajor = majorService.findAll();
//        cbbMajor.setModel(new DefaultComboBoxModel(listManageMajor.toArray()));
//        List<ManageSemester> listSemester = semesterService.findAll();
//        cbbSemester.setModel(new DefaultComboBoxModel(listSemester.toArray()));
    }

    private void loadTable() {
//        tblModel = (DefaultTableModel) tblStatistical.getModel();
//        ManageSubject subject = (ManageSubject) cbbSubjects.getSelectedItem();
//        ManageMajor major = (ManageMajor) cbbMajor.getSelectedItem();
//        ManageSemester semester = (ManageSemester) cbbSemester.getSelectedItem();
//        List<Statistical> list = managerService.findListStudent(subject.getCode(), major.getCode(), semester.getCode());
//        tblModel.setRowCount(0);
//        for (Statistical st : list) {
//            tblModel.addRow(new Object[]{st.getCode(),
//                st.getFullname(),
//                st.getScore(),
//                st.getScore() >= 5 ? "Đạt" : "Không đạt",
//                st.getClasscode() + " - " + st.getClassname()});
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
